# -*- coding: utf-8 -*-
"""Zomato data analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A7ctKpgtK4IAxLUUcXQ-Jd4SBKHULScX

# Project Objective :- Analyze restaurant trends using Zomato data

## Dataset Source :- https://media.geeksforgeeks.org/wp-content/uploads/20250117023324808265/Zomato-data-.csv

## Goal of the analysis:-better understand what influences ratings or popularity

### 1)Do a greater number of restaurants provide online delivery as opposed to offline services?
###    2)Which types of restaurants are the most favored by the general public?
###    3)What price range is preferred by couples for their dinner at restaurants?
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/Zomato-data-.csv')

"""### Basic Analysis"""

df.head()

"""### Change the rate column to float"""

def handleRate(value):
  value=str(value).split('/')
  value=value[0]
  return float(value)
df['rate']=df['rate'].apply(handleRate)

df.head()

df.info()

df.isnull().mean()

df.describe()

"""### Let’s explore the listed_in (type) column.



"""

sns.countplot(data=df,x='listed_in(type)')
plt.xlabel('Types of Restaurant')

"""#### Conclusion: The majority of the restaurants fall into the dining category."""

grouped_data=df.groupby('listed_in(type)')['rate'].mean()
result=pd.DataFrame({'rating':grouped_data})
sns.lineplot(data=result,x=result.index,y='rating')
plt.xlabel('Types of Restaurant')

"""##### Conclusion that dining restaurants has the worst ratings"""

grouped_data2=df.groupby('listed_in(type)')['votes'].sum()
result=pd.DataFrame({'votes':grouped_data2})
sns.lineplot(data=result,x=result.index,y='votes')
plt.xlabel('Types of Restaurant')

"""#### Conclusion: Dining restaurants are preferred by a larger number of individuals.

### Now we will determine the restaurant’s name that received the maximum votes based on a given dataframe.
"""

max_votes=df['votes'].max()
max_votes_name=df[df['votes']==max_votes]['name']
print('Restaurant(s) with the maximum votes:')
print(max_votes_name)

"""### Let’s explore the Online Order"""

sns.countplot(data=df,x='online_order')
plt.xlabel('Order Type')

"""#### Conclusion: This suggests that a majority of the restaurants do not accept online orders.

### Let’s explore the Rate column
"""

sns.histplot(data=df,x='rate',bins=5)
plt.xlabel('Rating')

"""#### Conclusion: The majority of restaurants received ratings ranging from 3.5 to 4.

### Let’s explore the approx_cost column.
"""

sns.countplot(data=df,x='approx_cost(for two people)')
plt.xlabel('Cost')

"""#### Conclusion: The majority of couples prefer restaurants with an approximate cost of 300 rupees.

### Now we will examine whether online orders receive higher ratings than offline orders.
"""

order_type_group=df.groupby('online_order')['rate'].mean()
result=pd.DataFrame({'rating':order_type_group})
sns.barplot(data=result,x=result.index,y='rating')
plt.xlabel('Order Type')

"""#### Conclusion: Offline orders received lower ratings in comparison to online orders, which obtained excellent ratings."""

pivot_table=df.pivot_table(index='listed_in(type)',columns='online_order',aggfunc='size')

sns.heatmap(pivot_table,annot=True)

"""#### Conclusion: Dining restaurants primarily accept offline orders, whereas cafes primarily receive online orders. This suggests that clients prefer to place orders in person at restaurants, but prefer online ordering at cafes.

### Now lets do some advance Visual Analysis
"""

sns.boxplot(data=df,x='rate',y='approx_cost(for two people)')

"""#### Conclusion: The median cost tends to increase as ratings go up. Lower‑rated restaurants (around 2.6–3.0) have medians closer to ₹300–₹400, whereas higher‑rated ones (around 4.2–4.6) sit nearer to ₹600–₹700."""

sns.scatterplot(data=df,x='votes',y='rate')

"""#### Conclusion:- Most restaurants cluster at low vote counts (under ~200 votes), showing that the vast majority receive only a handful of reviews."""